### ISSUE TITLE
Issues found when testing

### ISSUE THREAD

**Issue by TimKDJ** [juliuspf/reliabilityBayesian#9] opened 2020-05-20 15:08 UTC
For the most part the analyses seemed to work quite well! I've discovered 3 analysis errors and included some remarks that you may or may not wish to implement. Apologies for putting this in a single issue, butI think you're the only one working on this so I figured it'd be ok.

Frequentist:
- [x] `Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 8, 7` (seems to be caused by the "PFA" option in the "McDonalds's Estimation")***
- [x] `Error in cov(dataset, use = use.cases): no complete element pairs` (caused by listwise deletion -- there are no missing values in my selected columns though)***
- [x] I miss the ability to turn bootstrap sampling off. In other analyses where we include bootstrapping it's always optional.
- [x] The table "Fit Measures of Single Factor Model Fit" should have better names in the first column (e.g., rmsea.ci.lower -> Lower CI RMSEA)
- [x] Typo in "Boostrapped interval" qml option
- [x] "Cronbach's alpha Estimation" takes two selected radiobuttons? Guessing it's two different radiobutton groups, but that should be more obvious visually. 
- [x] It seems that the state doesn't work completely ok. Result tables are removed even though their dependencies didn't change (e.g., why does the scale table disappear if I change a item stat?). It also makes it less obvious what checkboxes change in the results when the results always disappear.
- [x] A confidence interval is usually an optional checkbox. It appears to be required in this analysis, are we trying to make a statement about always including CI's in papers or something? :p
- [x] It'd be nice if both the scale statistics and item statistics tables followed the same layout: in one table you have the stats in the rows in the other table in the columns.

Bayesian:
- [x] `Error in relyFit[['Bayes']][['chains']][[i]]: subscript out of bounds` (caused by "R-hat")***
- [x] Missing dot + space in footnote: `The following item correlated negatively with the scale: contGammaUsing 100 complete cases.`
- [x] Font of CI values in the posterior plots is quite tiny in relation to the other elements
- [x] Same as frequentist: the scale and item stat tables are inconsistent in how they present data (rows vs columns)
- [x] Feels a bit weird that the CI option under "Scale Statistics" influences the CI of the "Individual Item Statistics". Maybe place this elsewhere so it's more obvious it belongs to several groups?

*** [errors-reliability-module.zip](https://github.com/juliuspf/reliabilityBayesian/files/4657604/errors-reliability-module.zip) (Rename .zip to .jasp -- you do not need to unpack)

**Comment by juliuspf** [comment] 2020-05-28 08:40
About freq (3) and (8): That is more of a theoretical issue, our stand is, that it is a bad research practice to report only point estimates for reliability coefficients. One step towards redemption would be confidence intervals (most bootstrapped), but two steps would be credible intervals. Is this answering your question?

**Comment by juliuspf** [comment] 2020-05-28 09:12
about freq (9). I can change the layout for the scale statistics table, because the item statistics table would get too wide when a scale has many items.

**Comment by juliuspf** [comment] 2020-05-28 09:18
about freq (7): I dont really understand what you mean here?

**Comment by TimKDJ** [comment] 2020-05-28 12:31
> 
> 
> about freq (7): I dont really understand what you mean here?

Try running a Bayesian analysis and then when it is finished add an element that does not trigger a recompute of the main model. You will notice that the output window keeps the tables that were previously added and only the item that you requested gets added/changed.

Now try doing the same in the Frequentist analysis. Every single item you change in the input panel clears the output window...

**Comment by juliuspf** [comment] 2020-05-28 14:02
> > about freq (7): I dont really understand what you mean here?
> 
> Try running a Bayesian analysis and then when it is finished add an element that does not trigger a recompute of the main model. You will notice that the output window keeps the tables that were previously added and only the item that you requested gets added/changed.
> 
> Now try doing the same in the Frequentist analysis. Every single item you change in the input panel clears the output window...

I either don't understand it properly or I am failing to recreate it. I made a screen recording, which I cannot upload here. Should I send it via email, or what do you prefer?

**Comment by juliuspf** [comment] 2020-05-28 14:17
> * [ ]  It'd be nice if both the scale statistics and item statistics tables followed the same layout: in 

> * [ ]  Same as frequentist: the scale and item stat tables are inconsistent in how they present data (rows vs columns)

Okay. What I can do is make the scale statistics table look like the item statistics table, cause otherwise a large number of items would make the item table far too wide. What I am having trouble with is, how I would layout this? What I want is this 
![Screen Shot 2020-05-28 at 16 04 27](https://user-images.githubusercontent.com/38500953/83152923-a5adf580-a0fe-11ea-8ec6-d8c80fb62b87.png)

**Comment by vandenman** [comment] 2020-06-03 07:53
@TimKDJ I can't reproduce freq (7) either. I assume that there was something wrong with the position? In addition I found two more issues in the frequentist analysis:

- [ ] bug in credible interval, see screenshot below. Let the analysis run with only omega, then uncheck the credible intervals.

![image](https://user-images.githubusercontent.com/21319932/83610312-8a6c3b80-a57f-11ea-971c-512a6156e90d.png)

- [ ] A more pedantic issue. Check omega, alpha, omega if item dropped, and alpha if item dropped. Now uncheck alpha. The checkbox for alpha if item dropped is greyed out, but the item dropped table still shows the results for alpha.

![image](https://user-images.githubusercontent.com/21319932/83610521-d6b77b80-a57f-11ea-95c6-7284a3480611.png)

**Comment by juliuspf** [comment] 2020-06-04 12:16
Yes. thanks. About the second issue, I have no idea how to fix this. The alpha-item box is only enabled when the alpha box is, checking both and unchecking the alpha box creates this problem, because the alpha-item box remains checked internally (so far as you described). The table itself depends on both checkboxes, so it should change whenever one checkbox changes, but since the alpha-item box stays the same, the table keeps that column. What I am trying to say, is that, to me, the problem seems to be the checkboxes and how they relate to each other. But I dont know how to fix it. Any ideas?

**Comment by vandenman** [comment] 2020-06-04 12:32
well it's not a problem that the checkbox is shown checked in the gui, the problem is that the table shows that column. Wouldn't it be enough to set `if item dropped` to FALSE inside derivedoptions when the scale component is FALSE?

**Comment by juliuspf** [comment] 2020-06-04 12:35
well, ja I could write some lines to set every item-dropped-coefficient to false if the scale-coefficient is false

**Comment by vandenman** [comment] 2020-06-04 12:54
yeah that should do it!

**Closed** 2020-06-04 15:53 UTC
